musik_lib/urls.py
from django.urls import path
from musik_lib import views

app_name = 'lib'
urlpatterns = [
    # ex: /lib/
    path('', views.IndexView.as_view(), name='index'),

    # /collection
    path('collection/', views.CollectionListView.as_view(), name='collections'),
    # ex: /collection/1/
    path('collection/<int:pk>/', views.CollectionDetailView.as_view(), name='collection'),

    # ex: /track/
    path('track/', views.TrackListView.as_view(), name='track'),
    # ex: /track/5/
    path('track/<int:pk>/', views.TrackDetailView.as_view(), name='track'),

    # ex: /artist
    path('artist/', views.ArtistListView.as_view(), name='artists'),
    # ex: /artist/5/
    path('artist/<int:pk>/', views.ArtistDetailView.as_view(), name='artist'),

    # ex: /lib_stat/
    path('stats/', views.lib_stat, name='stats'),

    # ex: /collection_stat/
    path('collection_stat/', views.CollectionStatListView.as_view(), name='collections_stats'),
    # ex: /collection_stat/5/
    path('collection_stat/<int:pk>/', views.CollectionStatDetailView.as_view(), name='collection_stats'),

    # ex: /afc
    path('afc/', views.ArtistFrequencyCollectionListView.as_view(), name='afc'),
    # ex: /afc/5/
    path('afc/<int:pk>/', views.ArtistFrequencyCollectionDetailView.as_view(), name='afc'),

    # ex: /dt
    path('dt/', views.DuplicateTrackListView.as_view(), name='dts'),
    # ex: /dt/5/
    path('dt/<int:pk>/', views.DuplicateTrackDetailView.as_view(), name='dt'),

    # ex: /afl/
    path('afl/', views.ArtistFrequencyLibraryListView.as_view(), name='afls'),
    # ex: /afl/5/
    path('afl/<int:pk>/', views.ArtistFrequencyLibraryDetailView.as_view(), name='afl'),
]

musika/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('lib/', include('musik_lib.urls')),
    path('admin/', admin.site.urls),
]

musik_lib/models/base.py
import datetime
import operator

from itertools import chain
from functools import reduce

from django.db import models
from django.utils.translation import gettext_lazy

from musik_lib.validators import validate_year


def total_durations(durations):
    """
    Helper function to add durations
    :param durations:
    :return:
    """
    return reduce(operator.add, durations, datetime.timedelta())


def render_duration(duration):
    """
    Helper function to render duration
    0:ss for less than a minute songs
    m:ss for less than 10 minutes
    mm:ss for less than an hour
    h:mm:ss for more than an hour
    :param duration: a duration object (time delta)
    :return:
    """
    total_seconds = int(duration.total_seconds())
    seconds = (total_seconds % 3600) % 60
    minutes = (total_seconds % 3600) // 60
    hours = total_seconds // 3600

    if hours >= 24:
        days = hours // 24
        hours = hours % 24
        return "{} days and {}:{:02}:{:02} hours".format(days, hours, minutes, seconds)
    if hours:
        return "{}:{:02}:{:02} hours".format(hours, minutes, seconds)
    if minutes:
        return "{}:{:02} minutes".format(minutes, seconds)
    else:
        return "0:{:02} seconds".format(total_seconds)


class Artist(models.Model):
    """
        An artist
    """
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name

    @property
    def tracks(self):
        return [
            t for t
            in chain(
                self.main_artist.all(),
                self.featured_artist.all(),
            )
        ]


class Track(models.Model):
    """
        Music track
    """

    name = models.CharField(max_length=1000)
    duration = models.DurationField()
    released_year = models.PositiveSmallIntegerField(validators=[validate_year])

    artist = models.ManyToManyField(Artist, related_name='main_artist')
    featuring = models.ManyToManyField(Artist, related_name='featured_artist')

    def __str__(self):
        template = "{} - {} - {}"
        values = self.name, self.artist_names, render_duration(self.duration)
        return template.format(*values)

    @property
    def artist_names(self):
        artist_names = ""

        artists = self.artist.all()
        if artists:
            artist_names += " , ".join([a.name for a in artists])

        featuring = self.featuring.all()
        if featuring:
            artist_names += " Feat. " + " , ".join([a.name for a in featuring])

        return artist_names

    @property
    def artists(self):
        return [a for a in self.artist.all()] + [a for a in self.featuring.all()]

    @property
    def collections(self):
        tracks_in_collection = self.trackincollection_set.all() if hasattr(self, "trackincollection_set") else []
        return [t.collection for t in tracks_in_collection]


class Collection(models.Model):
    """
    Collection stores some tracks
    """

    name = models.CharField(max_length=200)
    nick_name = models.CharField(max_length=200, null=True)
    description = models.CharField(max_length=2000)

    created_year = models.PositiveSmallIntegerField(validators=[validate_year])
    ordinal = models.PositiveSmallIntegerField(unique=True, null=True)

    def __str__(self):
        template = "name={} , nick_name = {}, duration = {}"
        values = self.name, self.nick_name, render_duration(self.duration)
        return template.format(*values)

    @property
    def duration(self):
        return total_durations(
            [t.duration for t in self.tracks]
        )

    def number_of_tracks(self):
        return self.trackincollection_set.count() if hasattr(self, "trackincollection_set") else 0

    @property
    def tracks(self):
        return [t.track for t in self.trackincollection_set.order_by('ordinal')]

    def add_tracks(self, tracks):
        """

        :param tracks: Track objects. Assume that the order of this list maps to their order in the collection
        :return:
        """
        start_index = self.number_of_tracks() + 1
        for ind, track in enumerate(tracks):
            TrackInCollection.objects.create(track=track, collection=self, ordinal=start_index + ind)
        return self


class Album(models.Model):
    """
    Collection stores some tracks
    """

    name = models.CharField(max_length=200)
    created_year = models.PositiveSmallIntegerField(validators=[validate_year])
    spotify_id = models.CharField(max_length=50, null=True)

    class AlbumType(models.TextChoices):
        COMPILATION = 'CPN', gettext_lazy('Compilation')
        STUDIO = 'STD', gettext_lazy('Studio')

    album_type = models.CharField(
        max_length=3,
        choices=AlbumType.choices,
        default=AlbumType.COMPILATION,
    )

    def __str__(self):
        return f"{self.name} - {self.created_year}"

    def number_of_tracks(self):
        if not hasattr(self, "trackincollection_set"):
            return 0
        return self.trackincollection_set.count()

    @property
    def tracks(self):
        return [
            t.track for t
            in self.trackincollection_set
        ]

    def add_a_track(self, a_track: 'TrackInCollection'):
        """

        :param a_track: A TrackInCollcetion model
        :return: this instance
        """
        a_track.album = self
        a_track.save()
        return self


class TrackInCollection(models.Model):
    """
    A track in a collection; Separate from a track as it has a unique ordinal in the collection
    """
    track = models.ForeignKey(Track, on_delete=models.CASCADE)
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)
    album = models.ForeignKey(Album, on_delete=models.CASCADE, null=True)
    ordinal = models.PositiveSmallIntegerField()

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['collection', 'ordinal'], name='Collection and Ordinal')
        ]

    def __str__(self):
        return "track={} , ordinal = {}".format(self.track, self.ordinal)


class Library(models.Model):
    """
    The library holds all collections and it is a singleton class
    """

    def save(self, *args, **kwargs):
        self.pk = 1
        super(Library, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        pass

    @classmethod
    def load(cls):
        return cls.objects.get_or_create(pk=1)[0]

    @property
    def duration(self):
        return total_durations(
            [t.duration for t in self.collections]
        )

    @property
    def collections(self):
        return Collection.objects.all()

musik_lib/models/stats.py
from collections import defaultdict


from musik_lib.models.base import *


class LibraryStat(models.Model):
    library: Library = models.OneToOneField(
        Library,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    @classmethod
    def load(cls):
        obj, created = cls.objects.get_or_create(pk=1, library=Library.load())
        return obj

    @property
    def num_collections(self):
        return Collection.objects.count()

    @property
    def num_tracks(self):
        return Track.objects.count()

    @property
    def num_artists(self):
        return Artist.objects.count()

    @property
    def duration(self):
        return self.library.duration

    @property
    def rendered_duration(self) -> str:
        return render_duration(self.duration)

    def update(self):
        self.update_collection_stats()
        self.update_artist_frequency_counts()
        self.update_duplicate_tracks()

    def update_collection_stats(self):
        for coll in self.library.collections:
            c_stat, _ = CollectionStat.objects.get_or_create(collection=coll)
            c_stat.update()

    def update_artist_frequency_counts(self):
        """

        :return:
        """

        frequency_counts = defaultdict(int)
        unique_artists = dict()

        def add_collection_counts(cafcs):
            for cafc in cafcs:
                frequency_counts[cafc.artist.id] += cafc.frequency
                unique_artists[cafc.artist.id] = cafc.artist

        def add_artist_frequency_library(artist, frequency):
            afl, _ = ArtistFrequencyLibrary.objects.get_or_create(
                artist=artist,
                library_stat=self,
            )
            afl.frequency = frequency
            afl.save()
            self.artistfrequencylibrary_set.add(afl)

        for c_stat in self.collection_stats:
            add_collection_counts(c_stat.update_artist_frequency_counts())

        for aid, freq in frequency_counts.items():
            add_artist_frequency_library(unique_artists[aid], freq)
        
        return self.artistfrequencylibrary_set.all()

    @property
    def collection_stats(self):
        return CollectionStat.objects.all()

    def update_duplicate_tracks(self):
        track_counts = [
            (track, c_stat, track.trackincollection_set.count()) for c_stat in self.collection_stats
            for track in c_stat.collection.tracks
        ]
        duplicate_tracks = [tup for tup in track_counts if tup[2] > 1]

        for track, c_stat, frequency in duplicate_tracks:
            dt = DuplicateTrack.objects.get_or_create(track=track)[0]
            dt.frequency = frequency
            dt.save()
            c_stat.duplicate_tracks.add(dt)
            c_stat.save()
        return DuplicateTrack.objects.all()


class DuplicateTrack(models.Model):
    track = models.OneToOneField(
        Track,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    frequency = models.PositiveSmallIntegerField(default=2)

    def __str__(self):
        return "{} - {}".format(self.track, self.frequency)

    @property
    def name(self):
        return self.track.name


class CollectionStat(models.Model):
    """
    The stat extension of the collection model.

    """
    collection = models.OneToOneField(
        Collection,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    duplicate_tracks = models.ManyToManyField(DuplicateTrack)

    def __str__(self):
        return "Stats for {} ".format(self.collection.name)

    def update(self):
        self.update_artist_frequency_counts()

    def update_artist_frequency_counts(self):
        """

        :return: updated artist frequency counts of this collection stat
        """
        frequency_counts = defaultdict(int)
        unique_artists = dict()

        artists = [a for track in self.collection.tracks for a in track.artists]
        for artist in artists:
            frequency_counts[artist.id] += 1
            unique_artists[artist.id] = artist

        for artist_id, frequency in frequency_counts.items():
            artist = unique_artists[artist_id]
            afc = ArtistFrequencyCollection.objects.get_or_create(
                artist=artist,
                collection_stat=self,
            )[0]
            afc.frequency = frequency
            afc.save()
            self.artistfrequencycollection_set.add(afc)
        return self.artistfrequencycollection_set.all()


class ArtistFrequencyCollection(models.Model):
    artist = models.ForeignKey(
        Artist,
        on_delete=models.CASCADE,
    )
    collection_stat = models.ForeignKey(
        CollectionStat,
        on_delete=models.CASCADE
    )
    frequency = models.PositiveSmallIntegerField(default=1)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['artist', 'collection_stat'], name='Artist And Collection')
        ]

    def __str__(self):
        return "{} - {}".format(self.artist.name, self.frequency)

    @property
    def tracks(self):
        return [t for t in self.collection_stat.collection.tracks if t.artist == self.artist]


class ArtistFrequencyLibrary(models.Model):
    artist = models.ForeignKey(
        Artist,
        on_delete=models.CASCADE,
    )
    library_stat = models.ForeignKey(
        LibraryStat,
        on_delete=models.CASCADE
    )
    frequency = models.PositiveSmallIntegerField(default=1)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['artist', 'library_stat'], name='Artist And Library')
        ]

    def __str__(self):
        return "{} - {}".format(self.artist.name, self.frequency)

    @property
    def tracks(self):
        return self.artist.tracks

musik_lib/views.py
from django.db.models.functions import Upper
from django.shortcuts import render
from django.views import generic

from musik_lib.models.stats import *


class IndexView(generic.ListView):
    template_name = 'musik_lib/lib.html'
    context_object_name = 'collections'

    def get_queryset(self):
        return Collection.objects.order_by('ordinal')


def lib_stat(request):
    context = {
        "stats": LibraryStat.load(),
    }
    return render(request, 'musik_lib/lib_stat.html', context)


class CollectionDetailView(generic.DetailView):
    model = Collection
    template_name = 'musik_lib/collection.html'


class CollectionListView(generic.ListView):
    template_name = 'musik_lib/collection_list.html'
    context_object_name = 'collections'

    def get_queryset(self):
        """Return the last five published questions."""
        return Collection.objects.order_by('ordinal')


class TrackDetailView(generic.DetailView):
    model = Track
    template_name = 'musik_lib/track.html'


class TrackListView(generic.ListView):
    template_name = 'musik_lib/track_list.html'
    context_object_name = 'tracks'

    def get_queryset(self):
        """Return the last five published questions."""
        return Track.objects.order_by('name')


class ArtistDetailView(generic.DetailView):
    model = Artist
    template_name = 'musik_lib/artist.html'


class ArtistListView(generic.ListView):
    template_name = 'musik_lib/artist_list.html'
    context_object_name = 'artists'
    paginate_by = 100

    def get_queryset(self):
        return Artist.objects.order_by(Upper('name'))


class CollectionStatListView(generic.ListView):
    template_name = 'musik_lib/collections_stat_list.html'
    context_object_name = 'collections_stats'

    def get_queryset(self):
        return CollectionStat.objects.order_by('collection_id')


class CollectionStatDetailView(generic.DetailView):
    model = CollectionStat
    template_name = 'musik_lib/collection_stat.html'
    context_object_name = 'c_stat'


class DuplicateTrackDetailView(generic.DetailView):
    model = DuplicateTrack
    template_name = 'musik_lib/duplicate_track.html'
    context_object_name = 'dt'


class DuplicateTrackListView(generic.ListView):
    template_name = 'musik_lib/dt_list.html'
    context_object_name = 'dts'

    def get_queryset(self):
        """Return the last five published questions."""
        return DuplicateTrack.objects.all()


class ArtistFrequencyCollectionDetailView(generic.DetailView):
    model = ArtistFrequencyCollection
    template_name = 'musik_lib/afc.html'
    context_object_name = 'afc'


class ArtistFrequencyCollectionListView(generic.ListView):
    template_name = 'musik_lib/afc_list.html'
    context_object_name = 'afcs'

    def get_queryset(self):
        return ArtistFrequencyCollection.objects.order_by('-frequency', Upper("artist__name"))


class ArtistFrequencyLibraryDetailView(generic.DetailView):
    model = ArtistFrequencyLibrary
    template_name = 'musik_lib/afl.html'
    context_object_name = 'afl'


class ArtistFrequencyLibraryListView(generic.ListView):
    template_name = 'musik_lib/afl_list.html'
    context_object_name = 'afls'

    def get_queryset(self):
        return ArtistFrequencyLibrary.objects.order_by('-frequency', Upper("artist__name"))

musik_lib/templates/musik_lib/Collection.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Collection</title>


</head>
<body>
     <h1>{{ collection }}</h1>
        <ol>
            {% for t in collection.track_set.all %}
                <li><a href="/lib/track/{{ t.id }}/">{{ t }}</a></li>
            {% endfor %}
        </ol>
</body>
</html>

musik_lib/templates/musik_lib/Lib.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Library</title>
        {% if collections %}
        <ul>
        {% for c in collections %}
            <li><a href="/lib/collection/{{ c.id }}/">{{ c.name }}</a></li>
        {% endfor %}
        </ul>
        {% else %}
        <p>No collections are available.</p>
        {% endif %}
</head>
<body>

</body>
</html>

musik_lib/templates/musik_lib/Track.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Track</title>
</head>
<body>
     <h1>{{ track }}</h1>
        <ul>
            {% for a in track.artist_set.all %}
                <li><a href="/lib/artist/{{ a.id }}/">{{ a.name }}</a></li>
            {% endfor %}
        </ul>
</body>
</html>

musik_lib/templates/musik_lib/afc.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Artist Frequency Collection</title>
</head>
<body>
     <h1>
         <a href="/lib/artist/{{ afc.artist_id }}/">{{ afc.artist }}</a>
         -
         <a href="/lib/collection_stat/{{ afc.collection_stat_id }}/">{{ afc.collection_stat.collection.name }}</a>


         - {{ afc.frequency }}
     </h1>
        <ol>
            {% for t in afc.tracks %}
                <li><a href="/lib/track/{{ t.id }}/">{{ t }}</a></li>
            {% endfor %}
        </ol>

</body>
</html>

musik_lib/templates/musik_lib/afl.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Artist Frequency Library</title>
</head>
<body>
     <h1>
         <a href="/lib/artist/{{ afl.artist_id }}/">{{ afl.artist }}</a>
         - {{ afl.frequency }}
     </h1>
        <ol>
            {% for t in afl.tracks %}
                {% for c in t.collections %}
                            <li>
                                <a href="/lib/track/{{ t.id }}/">{{ t }} </a>
                                ::
                                <a href="/lib/collection/{{ c.id }}/">{{ c.name }}</a>
                            </li>
                {% endfor %}
            {% endfor %}
        </ol>

</body>
</html>

musik_lib/templates/musik_lib/artist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Artist</title>
</head>
<body>
     <h1>{{ artist }}</h1>

        <ol>
            {% for t in artist.tracks %}
                <li><a href="/lib/track/{{ t.id }}/">{{ t }}</a>
                    <ul>
                        {% for c in t.collections %}
                            <li><a href="/lib/collection/{{ c.id }}/">{{ c.name }}</a></li>
                        {% endfor %}
                     </ul>
                </li>
            {% endfor %}
        </ol>

</body>
</html>

musik_lib/templates/musik_lib/collection.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Collection</title>


</head>
<body>
     <h1>{{ collection }}</h1>
        <ol>
            {% for t in collection.tracks %}
                <li><a href="/lib/track/{{ t.id }}/">{{ t }}</a></li>
            {% endfor %}
        </ol>
</body>
</html>

musik_lib/templates/musik_lib/collection_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Collections</title>
    <h1> Collections </h1>
        <ol>
        {% for c in collections %}
            <li><a href="/lib/collection/{{ c.id }}/">{{ c }}</a></li>
        {% endfor %}
        </ol>
</head>
<body>

</body>
</html>

musik_lib/templates/musik_lib/collection_stat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Collection Stats</title>


</head>
<body>
    <h1> <a href="/lib/collection/{{ c_stat.collection.id }}/">{{ c_stat.collection }}</a> </h1>
    <h1>{{ c_stat }}</h1>
     <h1> Artist Frequencies </h1>
        <ol>
            {% for afc in c_stat.artistfrequencycollection_set.all %}
                <li><a href="/lib/afc/{{ afc.id }}/">{{ afc }}</a></li>
            {% endfor %}
        </ol>
        {% if c_stat.duplicate_tracks.all %}
        <h1>Duplicate Tracks</h1>
            <ol>
                {% for dt in c_stat.duplicate_tracks.all %}
                    <li><a href="/lib/dt/{{ dt.pk }}/">{{ dt.track.name }}</a></li>
                {% endfor %}
            </ol>
            {% else %}
            <p>No Duplicate Tracks.</p>
        {% endif %}
</body>
</html>

musik_lib/templates/musik_lib/collections_stat_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Collections Stats</title>
        {% if collections_stats %}
        <ol>
        {% for c in collections_stats %}
            <li><a href="/lib/collection_stat/{{ c.collection_id }}/">{{ c }}</a></li>
        {% endfor %}
        </ol>
        {% else %}
        <p>No collection stats are available.</p>
        {% endif %}
</head>
<body>

</body>
</html>

musik_lib/templates/musik_lib/collections_stats.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Collections Stats</title>
        {% if collections_stats %}
        <ul>
        {% for c in collections_stats %}
            <li><a href="/lib/collection_stat/{{ c.collection_id }}/">{{ c }}</a></li>
        {% endfor %}
        </ul>
        {% else %}
        <p>No collection stats are available.</p>
        {% endif %}
</head>
<body>

</body>
</html>

musik_lib/templates/musik_lib/duplicate_track.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Duplicate Track</title>
</head>
<body>
     <h1><a href="/lib/track/{{ dt.track_id }}/">{{ dt.track }}</a></h1>
        <ul>
            {% for c in dt.track.collections %}
                <li><a href="/lib/collection/{{ c.id }}/">{{ c }}</a></li>
            {% endfor %}
        </ul>
</body>
</html>

musik_lib/templates/musik_lib/track.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Track</title>
</head>
<body>
     <h1>{{ track }} - {{  track.released_year }}</h1>
     <p>  Artists  </p>
        <ul>
            {% for a in track.artists %}
                <li><a href="/lib/artist/{{ a.id }}/">{{ a.name }}</a></li>
            {% endfor %}
        </ul>
     <p>  Collections  </p>
        <ul>
            {% for c in track.collections %}
                <li><a href="/lib/collection/{{ c.id }}/">{{ c.name }}</a></li>
            {% endfor %}
        </ul>
</body>
</html>

musik_lib/templates/musik_lib/track_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tracks</title>
        <ol>
        {% for t in tracks %}
            <li><a href="/lib/track/{{ t.id }}/">{{ t }}</a></li>
        {% endfor %}
        </ol>
</head>
<body>

</body>
</html>